version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    networks:
      - merchie-app
  merchie:
    build: 
      dockerfile: Dockerfile
      context: ./merchie
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - merchie-app
  merchie-backend:
    build: 
      dockerfile: Dockerfile
      context: './merchie-backend'
    ports:
      - '5000:5000'
    networks:
      - merchie-app
networks:
  merchie-app:
    driver: bridge
